add：connect nats userinfo option
Jeffail/benthos pull request #561
Opened 2020-11-18 12:42 UTC by CodingJzy

* When the input type is nats, support username and password authentication

2020-11-18 19:45 UTC, Jeffail requested changes
Hey @CodingJzy, looking good. Added a couple of comments just to make the field names more consistent. If we're adding auth fields to one nats component then I'd also want to make sure we add them to all others (the `nats` output and also the `nats_steam` input and output).

You can also delete `nats_test.go` as the integration tests are here: https://github.com/Jeffail/benthos/blob/master/lib/test/integration/nats_test.go

2020-11-18 19:45 UTC, Jeffail commented on lib/input/reader/nats.go
> +	UserName      string   `json:"user_name" yaml:"username"`
```suggestion
	Username      string   `json:"username" yaml:"username"`
```

2020-11-18 19:45 UTC, Jeffail commented on lib/input/reader/nats.go
> +	if n.conf.UserName != "" || n.conf.Password != "" {
```suggestion
	if n.conf.Username != "" || n.conf.Password != "" {
```

2020-11-19 01:45 UTC, CodingJzy commented
Ok ! thanks for your guidance

2020-11-19 04:57 UTC, CodingJzy commented
@Jeffail  hey :grin:  In fact. I found that nats and nats-streaming officially support url semantics. e.g. nats://root:pass@localhost:4222

2020-11-20 17:38 UTC, Jeffail commented
> @Jeffail hey grin In fact. I found that nats and nats-streaming officially support url semantics. e.g. nats://root:pass@localhost:4222

Ahhh, in that case it's probably cleaner to document that syntax rather than add more fields, I've added examples with: https://github.com/Jeffail/benthos/commit/64ad8d480b9eb99e458ed543375b84c63c8211ea

Closing this PR for now but thanks for raising it and for the investigation.

2020-11-20 17:38 UTC, closed without merging